<?php

namespace ContainerYGFBVNL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sn23N7WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sn23N7W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sn23N7W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'PromoRepository' => ['privates', 'App\\Repository\\PromoRepository', 'getPromoRepositoryService', true],
            'UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'PromoRepository' => 'App\\Repository\\PromoRepository',
            'UserRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
