<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRYvGgOS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRYvGgOS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRYvGgOS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRYvGgOS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRYvGgOS\App_KernelDevDebugContainer([
    'container.build_hash' => 'RYvGgOS',
    'container.build_id' => '2979e370',
    'container.build_time' => 1683291529,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRYvGgOS');
