<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWAvTxR3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWAvTxR3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWAvTxR3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWAvTxR3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWAvTxR3\App_KernelDevDebugContainer([
    'container.build_hash' => 'WAvTxR3',
    'container.build_id' => '0d0650bc',
    'container.build_time' => 1682325433,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWAvTxR3');
