<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY3Tgpk9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY3Tgpk9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY3Tgpk9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY3Tgpk9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY3Tgpk9\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y3Tgpk9',
    'container.build_id' => 'a57a7769',
    'container.build_time' => 1683019578,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY3Tgpk9');
