<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNz23Nko\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNz23Nko/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNz23Nko.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNz23Nko\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNz23Nko\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nz23Nko',
    'container.build_id' => 'efc073d4',
    'container.build_time' => 1678118652,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNz23Nko');
