<?php

namespace Container4zWx4Pw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordMatchValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\PasswordMatchValidator' shared autowired service.
     *
     * @return \App\Form\PasswordMatchValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Form/PasswordMatchValidator.php';

        return $container->privates['App\\Form\\PasswordMatchValidator'] = new \App\Form\PasswordMatchValidator();
    }
}
