controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: GET

login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST