<?php

namespace ContainerHlCBVrV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ISQ48riService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ISQ48ri' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ISQ48ri'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'InfoRepository' => ['privates', '.errored.i.Xd6j8', NULL, 'Cannot determine controller argument for "App\\Controller\\BaseCController::index5()": the $InfoRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\InfoRepository".'],
            'StageRepository' => ['privates', 'App\\Repository\\StageRepository', 'getStageRepositoryService', true],
        ], [
            'InfoRepository' => '?',
            'StageRepository' => 'App\\Repository\\StageRepository',
        ]);
    }
}
