<?php

namespace ContainerHlCBVrV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_I_Xd6j8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.i.Xd6j8' shared service.
     *
     * @return \App\Repository\InfoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\BaseCController::index5()": the $InfoRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\InfoRepository".');
    }
}
